// <auto-generated />
namespace UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class stats_to_story : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stats_to_story));
        
        string IMigrationMetadata.Id
        {
            get { return "201508192246468_stats_to_story"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
